name: application6
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
 

dependencies:
    cached_network_image: ^3.2.3
    firebase_auth: ^4.10.0
    firebase_core: ^2.16.0
    flutter:
      sdk: flutter 
    flutter_svg: ^2.0.7
    intl: ^0.18.1
flutter: 
sdk: flutter
cached_network_image: ^3.2.1
flutter_svg: ^1.1.6
intl: ^0.18.0

#Firebase auth and firebase core
firebase_core: ^2.16.0
firebase_auth: ^4.10.0

dev_dependencies: 
flutter_test: 

 
uses-material-design: true
assets: 
    - assets/
    - assets/images/
fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
